<?php

namespace Khalyomede\Systempay;

class TransactionStatus
{
    const AUTHORISED = "AUTHORISED";
    const ABANDONED = "ABANDONED";
    const ACCEPTED = "ACCEPTED";
    const AUTHORISED_TO_VALIDATE = "AUTHORISED_TO_VALIDATE";
    const CANCELLED = "CANCELLED";
    const CAPTURED = "CAPTURED";
    const CAPTURE_FAILED = "CAPTURE_FAILED";
    const EXPIRED = "EXPIRED";
    const PENDING = "INITIAL";
    const NOT_CREATED = "NOT_CREATED";
    const REFUSED = "REFUSED";
    const SUSPENDED = "SUSPENDED";
    const UNDER_VERIFICATION = "UNDER_VERIFICATION";
    const WAITING_AUTHORISATION = "WAITING_AUTHORISATION";
    const WAITING_AUTHORISATION_TO_VALIDATE = "WAITING_AUTHORISATION_TO_VALIDATE";
}
